/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GeminiSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "",
  model: "gemini-2.5-flash",
  syncFolder: "",
  corpusName: "",
  corpusDisplayName: "Obsidian Vault",
  autoSync: true,
  syncDebounceMs: 3e3,
  files: {}
};
var GeminiSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: "Gemini Sync Settings" });
    containerEl.createEl("h2", { text: "API Configuration" });
    new import_obsidian.Setting(containerEl).setName("Gemini API Key").setDesc("Enter your Google Gemini API key. Get one from Google AI Studio.").addText(
      (text) => text.setPlaceholder("Enter your API key").setValue(this.plugin.settings.apiKey ? "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022" : "").onChange(async (value) => {
        if (value && !value.includes("\u2022")) {
          this.plugin.settings.apiKey = value;
          await this.plugin.saveSettings();
        }
      }).inputEl.type = "password"
    ).addButton(
      (button) => button.setButtonText("Verify").onClick(async () => {
        if (!this.plugin.settings.apiKey) {
          new import_obsidian.Notice("Please enter an API key first");
          return;
        }
        button.setButtonText("Verifying...");
        const isValid = await this.plugin.geminiService.verifyApiKey();
        if (isValid) {
          new import_obsidian.Notice("API key is valid!");
          button.setButtonText("Verified \u2713");
        } else {
          new import_obsidian.Notice("Invalid API key. Please check and try again.");
          button.setButtonText("Verify");
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Gemini Model").setDesc("Select the Gemini model to use for chat. Gemini 2.5 Flash is recommended for best performance.").addDropdown((dropdown) => {
      dropdown.addOption("gemini-2.5-flash", "Gemini 2.5 Flash - Latest (Recommended)");
      dropdown.addOption("gemini-2.0-flash-exp", "Gemini 2.0 Flash (Experimental)");
      dropdown.addOption("gemini-1.5-flash-latest", "Gemini 1.5 Flash (Latest)");
      dropdown.addOption("gemini-1.5-flash-8b", "Gemini 1.5 Flash 8B");
      dropdown.addOption("gemini-1.5-flash", "Gemini 1.5 Flash");
      dropdown.addOption("gemini-1.5-pro-latest", "Gemini 1.5 Pro (Latest)");
      dropdown.addOption("gemini-1.5-pro", "Gemini 1.5 Pro");
      dropdown.setValue(this.plugin.settings.model);
      dropdown.onChange(async (value) => {
        this.plugin.settings.model = value;
        await this.plugin.saveSettings();
        this.plugin.geminiService.refreshClient();
        new import_obsidian.Notice(`Model changed to ${value}`);
      });
    });
    containerEl.createEl("h2", { text: "Sync Configuration" });
    new import_obsidian.Setting(containerEl).setName("Sync Folder").setDesc("Select the folder to sync with Gemini. All markdown files in this folder (including subfolders) will be synced.").addDropdown((dropdown) => {
      dropdown.addOption("", "-- Select a folder --");
      const folders = this.getAllFolders();
      folders.forEach((folder) => {
        dropdown.addOption(folder, folder);
      });
      dropdown.setValue(this.plugin.settings.syncFolder);
      dropdown.onChange(async (value) => {
        this.plugin.settings.syncFolder = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Corpus Display Name").setDesc("A friendly name for your knowledge base in Gemini.").addText(
      (text) => text.setPlaceholder("My Obsidian Vault").setValue(this.plugin.settings.corpusDisplayName).onChange(async (value) => {
        this.plugin.settings.corpusDisplayName = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto Sync").setDesc("Automatically sync files when they are created, modified, or deleted.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
        this.plugin.settings.autoSync = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync Debounce (ms)").setDesc("Wait time before syncing after a file change. Helps reduce API calls during rapid edits.").addText(
      (text) => text.setPlaceholder("3000").setValue(String(this.plugin.settings.syncDebounceMs)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.syncDebounceMs = num;
          await this.plugin.saveSettings();
        }
      })
    );
    containerEl.createEl("h2", { text: "Sync Dashboard" });
    const dashboardEl = containerEl.createDiv({ cls: "gemini-sync-dashboard" });
    this.renderDashboard(dashboardEl);
    containerEl.createEl("h2", { text: "Actions" });
    new import_obsidian.Setting(containerEl).setName("Force Full Sync").setDesc("Re-sync all files in the sync folder. Use this if sync status seems incorrect.").addButton(
      (button) => button.setButtonText("Sync Now").setCta().onClick(async () => {
        if (!this.plugin.settings.apiKey) {
          new import_obsidian.Notice("Please configure your API key first");
          return;
        }
        if (!this.plugin.settings.syncFolder) {
          new import_obsidian.Notice("Please select a sync folder first");
          return;
        }
        button.setButtonText("Syncing...");
        button.setDisabled(true);
        try {
          await this.plugin.syncEngine.fullSync();
          new import_obsidian.Notice("Full sync completed!");
          this.display();
        } catch (error) {
          new import_obsidian.Notice("Sync failed. Check console for details.");
          console.error("Sync error:", error);
        } finally {
          button.setButtonText("Sync Now");
          button.setDisabled(false);
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Clear Sync Data").setDesc("Remove all local sync mappings. Does NOT delete files from Gemini.").addButton(
      (button) => button.setButtonText("Clear").setWarning().onClick(async () => {
        this.plugin.settings.files = {};
        this.plugin.settings.corpusName = "";
        await this.plugin.saveSettings();
        new import_obsidian.Notice("Sync data cleared");
        this.display();
      })
    );
    containerEl.createEl("h2", { text: "Help" });
    const helpEl = containerEl.createDiv({ cls: "gemini-sync-help" });
    helpEl.createEl("p", {
      text: "This plugin syncs your Obsidian notes with Google Gemini's File Search API, enabling you to chat with your notes using AI."
    });
    helpEl.createEl("p", {
      text: "\u26A0\uFE0F Note: Using this plugin may incur costs on your Google Cloud account depending on usage."
    });
    helpEl.createEl("a", {
      text: "Get API Key from Google AI Studio",
      href: "https://aistudio.google.com/app/apikey"
    });
  }
  getAllFolders() {
    const folders = [];
    const rootFolder = this.app.vault.getRoot();
    const collectFolders = (folder, path = "") => {
      for (const child of folder.children) {
        if (child instanceof import_obsidian.TFolder) {
          const fullPath = path ? `${path}/${child.name}` : child.name;
          folders.push(fullPath);
          collectFolders(child, fullPath);
        }
      }
    };
    collectFolders(rootFolder);
    folders.sort();
    return folders;
  }
  renderDashboard(container) {
    const files = this.plugin.settings.files;
    const fileCount = Object.keys(files).length;
    let syncedCount = 0;
    let pendingCount = 0;
    let errorCount = 0;
    for (const path in files) {
      const status = files[path].status;
      if (status === "synced")
        syncedCount++;
      else if (status === "pending")
        pendingCount++;
      else if (status === "error")
        errorCount++;
    }
    const statsEl = container.createDiv({ cls: "sync-stats" });
    statsEl.createEl("div", {
      cls: "sync-stat",
      text: `\u{1F4C1} Total Files: ${fileCount}`
    });
    statsEl.createEl("div", {
      cls: "sync-stat sync-stat-success",
      text: `\u{1F7E2} Synced: ${syncedCount}`
    });
    statsEl.createEl("div", {
      cls: "sync-stat sync-stat-pending",
      text: `\u{1F7E1} Pending: ${pendingCount}`
    });
    statsEl.createEl("div", {
      cls: "sync-stat sync-stat-error",
      text: `\u{1F534} Errors: ${errorCount}`
    });
    if (this.plugin.settings.corpusName) {
      container.createEl("div", {
        cls: "sync-corpus-info",
        text: `Corpus: ${this.plugin.settings.corpusDisplayName}`
      });
    }
    if (this.plugin.settings.syncFolder) {
      container.createEl("div", {
        cls: "sync-folder-info",
        text: `Watching: ${this.plugin.settings.syncFolder}/`
      });
    }
  }
};

// node_modules/@google/generative-ai/dist/index.mjs
var SchemaType;
(function(SchemaType2) {
  SchemaType2["STRING"] = "string";
  SchemaType2["NUMBER"] = "number";
  SchemaType2["INTEGER"] = "integer";
  SchemaType2["BOOLEAN"] = "boolean";
  SchemaType2["ARRAY"] = "array";
  SchemaType2["OBJECT"] = "object";
})(SchemaType || (SchemaType = {}));
var ExecutableCodeLanguage;
(function(ExecutableCodeLanguage2) {
  ExecutableCodeLanguage2["LANGUAGE_UNSPECIFIED"] = "language_unspecified";
  ExecutableCodeLanguage2["PYTHON"] = "python";
})(ExecutableCodeLanguage || (ExecutableCodeLanguage = {}));
var Outcome;
(function(Outcome2) {
  Outcome2["OUTCOME_UNSPECIFIED"] = "outcome_unspecified";
  Outcome2["OUTCOME_OK"] = "outcome_ok";
  Outcome2["OUTCOME_FAILED"] = "outcome_failed";
  Outcome2["OUTCOME_DEADLINE_EXCEEDED"] = "outcome_deadline_exceeded";
})(Outcome || (Outcome = {}));
var POSSIBLE_ROLES = ["user", "model", "function", "system"];
var HarmCategory;
(function(HarmCategory2) {
  HarmCategory2["HARM_CATEGORY_UNSPECIFIED"] = "HARM_CATEGORY_UNSPECIFIED";
  HarmCategory2["HARM_CATEGORY_HATE_SPEECH"] = "HARM_CATEGORY_HATE_SPEECH";
  HarmCategory2["HARM_CATEGORY_SEXUALLY_EXPLICIT"] = "HARM_CATEGORY_SEXUALLY_EXPLICIT";
  HarmCategory2["HARM_CATEGORY_HARASSMENT"] = "HARM_CATEGORY_HARASSMENT";
  HarmCategory2["HARM_CATEGORY_DANGEROUS_CONTENT"] = "HARM_CATEGORY_DANGEROUS_CONTENT";
})(HarmCategory || (HarmCategory = {}));
var HarmBlockThreshold;
(function(HarmBlockThreshold2) {
  HarmBlockThreshold2["HARM_BLOCK_THRESHOLD_UNSPECIFIED"] = "HARM_BLOCK_THRESHOLD_UNSPECIFIED";
  HarmBlockThreshold2["BLOCK_LOW_AND_ABOVE"] = "BLOCK_LOW_AND_ABOVE";
  HarmBlockThreshold2["BLOCK_MEDIUM_AND_ABOVE"] = "BLOCK_MEDIUM_AND_ABOVE";
  HarmBlockThreshold2["BLOCK_ONLY_HIGH"] = "BLOCK_ONLY_HIGH";
  HarmBlockThreshold2["BLOCK_NONE"] = "BLOCK_NONE";
})(HarmBlockThreshold || (HarmBlockThreshold = {}));
var HarmProbability;
(function(HarmProbability2) {
  HarmProbability2["HARM_PROBABILITY_UNSPECIFIED"] = "HARM_PROBABILITY_UNSPECIFIED";
  HarmProbability2["NEGLIGIBLE"] = "NEGLIGIBLE";
  HarmProbability2["LOW"] = "LOW";
  HarmProbability2["MEDIUM"] = "MEDIUM";
  HarmProbability2["HIGH"] = "HIGH";
})(HarmProbability || (HarmProbability = {}));
var BlockReason;
(function(BlockReason2) {
  BlockReason2["BLOCKED_REASON_UNSPECIFIED"] = "BLOCKED_REASON_UNSPECIFIED";
  BlockReason2["SAFETY"] = "SAFETY";
  BlockReason2["OTHER"] = "OTHER";
})(BlockReason || (BlockReason = {}));
var FinishReason;
(function(FinishReason2) {
  FinishReason2["FINISH_REASON_UNSPECIFIED"] = "FINISH_REASON_UNSPECIFIED";
  FinishReason2["STOP"] = "STOP";
  FinishReason2["MAX_TOKENS"] = "MAX_TOKENS";
  FinishReason2["SAFETY"] = "SAFETY";
  FinishReason2["RECITATION"] = "RECITATION";
  FinishReason2["LANGUAGE"] = "LANGUAGE";
  FinishReason2["OTHER"] = "OTHER";
})(FinishReason || (FinishReason = {}));
var TaskType;
(function(TaskType2) {
  TaskType2["TASK_TYPE_UNSPECIFIED"] = "TASK_TYPE_UNSPECIFIED";
  TaskType2["RETRIEVAL_QUERY"] = "RETRIEVAL_QUERY";
  TaskType2["RETRIEVAL_DOCUMENT"] = "RETRIEVAL_DOCUMENT";
  TaskType2["SEMANTIC_SIMILARITY"] = "SEMANTIC_SIMILARITY";
  TaskType2["CLASSIFICATION"] = "CLASSIFICATION";
  TaskType2["CLUSTERING"] = "CLUSTERING";
})(TaskType || (TaskType = {}));
var FunctionCallingMode;
(function(FunctionCallingMode2) {
  FunctionCallingMode2["MODE_UNSPECIFIED"] = "MODE_UNSPECIFIED";
  FunctionCallingMode2["AUTO"] = "AUTO";
  FunctionCallingMode2["ANY"] = "ANY";
  FunctionCallingMode2["NONE"] = "NONE";
})(FunctionCallingMode || (FunctionCallingMode = {}));
var DynamicRetrievalMode;
(function(DynamicRetrievalMode2) {
  DynamicRetrievalMode2["MODE_UNSPECIFIED"] = "MODE_UNSPECIFIED";
  DynamicRetrievalMode2["MODE_DYNAMIC"] = "MODE_DYNAMIC";
})(DynamicRetrievalMode || (DynamicRetrievalMode = {}));
var GoogleGenerativeAIError = class extends Error {
  constructor(message) {
    super(`[GoogleGenerativeAI Error]: ${message}`);
  }
};
var GoogleGenerativeAIResponseError = class extends GoogleGenerativeAIError {
  constructor(message, response) {
    super(message);
    this.response = response;
  }
};
var GoogleGenerativeAIFetchError = class extends GoogleGenerativeAIError {
  constructor(message, status, statusText, errorDetails) {
    super(message);
    this.status = status;
    this.statusText = statusText;
    this.errorDetails = errorDetails;
  }
};
var GoogleGenerativeAIRequestInputError = class extends GoogleGenerativeAIError {
};
var DEFAULT_BASE_URL = "https://generativelanguage.googleapis.com";
var DEFAULT_API_VERSION = "v1beta";
var PACKAGE_VERSION = "0.21.0";
var PACKAGE_LOG_HEADER = "genai-js";
var Task;
(function(Task2) {
  Task2["GENERATE_CONTENT"] = "generateContent";
  Task2["STREAM_GENERATE_CONTENT"] = "streamGenerateContent";
  Task2["COUNT_TOKENS"] = "countTokens";
  Task2["EMBED_CONTENT"] = "embedContent";
  Task2["BATCH_EMBED_CONTENTS"] = "batchEmbedContents";
})(Task || (Task = {}));
var RequestUrl = class {
  constructor(model, task, apiKey, stream, requestOptions) {
    this.model = model;
    this.task = task;
    this.apiKey = apiKey;
    this.stream = stream;
    this.requestOptions = requestOptions;
  }
  toString() {
    var _a, _b;
    const apiVersion = ((_a = this.requestOptions) === null || _a === void 0 ? void 0 : _a.apiVersion) || DEFAULT_API_VERSION;
    const baseUrl = ((_b = this.requestOptions) === null || _b === void 0 ? void 0 : _b.baseUrl) || DEFAULT_BASE_URL;
    let url = `${baseUrl}/${apiVersion}/${this.model}:${this.task}`;
    if (this.stream) {
      url += "?alt=sse";
    }
    return url;
  }
};
function getClientHeaders(requestOptions) {
  const clientHeaders = [];
  if (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.apiClient) {
    clientHeaders.push(requestOptions.apiClient);
  }
  clientHeaders.push(`${PACKAGE_LOG_HEADER}/${PACKAGE_VERSION}`);
  return clientHeaders.join(" ");
}
async function getHeaders(url) {
  var _a;
  const headers = new Headers();
  headers.append("Content-Type", "application/json");
  headers.append("x-goog-api-client", getClientHeaders(url.requestOptions));
  headers.append("x-goog-api-key", url.apiKey);
  let customHeaders = (_a = url.requestOptions) === null || _a === void 0 ? void 0 : _a.customHeaders;
  if (customHeaders) {
    if (!(customHeaders instanceof Headers)) {
      try {
        customHeaders = new Headers(customHeaders);
      } catch (e) {
        throw new GoogleGenerativeAIRequestInputError(`unable to convert customHeaders value ${JSON.stringify(customHeaders)} to Headers: ${e.message}`);
      }
    }
    for (const [headerName, headerValue] of customHeaders.entries()) {
      if (headerName === "x-goog-api-key") {
        throw new GoogleGenerativeAIRequestInputError(`Cannot set reserved header name ${headerName}`);
      } else if (headerName === "x-goog-api-client") {
        throw new GoogleGenerativeAIRequestInputError(`Header name ${headerName} can only be set using the apiClient field`);
      }
      headers.append(headerName, headerValue);
    }
  }
  return headers;
}
async function constructModelRequest(model, task, apiKey, stream, body, requestOptions) {
  const url = new RequestUrl(model, task, apiKey, stream, requestOptions);
  return {
    url: url.toString(),
    fetchOptions: Object.assign(Object.assign({}, buildFetchOptions(requestOptions)), { method: "POST", headers: await getHeaders(url), body })
  };
}
async function makeModelRequest(model, task, apiKey, stream, body, requestOptions = {}, fetchFn = fetch) {
  const { url, fetchOptions } = await constructModelRequest(model, task, apiKey, stream, body, requestOptions);
  return makeRequest(url, fetchOptions, fetchFn);
}
async function makeRequest(url, fetchOptions, fetchFn = fetch) {
  let response;
  try {
    response = await fetchFn(url, fetchOptions);
  } catch (e) {
    handleResponseError(e, url);
  }
  if (!response.ok) {
    await handleResponseNotOk(response, url);
  }
  return response;
}
function handleResponseError(e, url) {
  let err = e;
  if (!(e instanceof GoogleGenerativeAIFetchError || e instanceof GoogleGenerativeAIRequestInputError)) {
    err = new GoogleGenerativeAIError(`Error fetching from ${url.toString()}: ${e.message}`);
    err.stack = e.stack;
  }
  throw err;
}
async function handleResponseNotOk(response, url) {
  let message = "";
  let errorDetails;
  try {
    const json = await response.json();
    message = json.error.message;
    if (json.error.details) {
      message += ` ${JSON.stringify(json.error.details)}`;
      errorDetails = json.error.details;
    }
  } catch (e) {
  }
  throw new GoogleGenerativeAIFetchError(`Error fetching from ${url.toString()}: [${response.status} ${response.statusText}] ${message}`, response.status, response.statusText, errorDetails);
}
function buildFetchOptions(requestOptions) {
  const fetchOptions = {};
  if ((requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.signal) !== void 0 || (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeout) >= 0) {
    const controller = new AbortController();
    if ((requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeout) >= 0) {
      setTimeout(() => controller.abort(), requestOptions.timeout);
    }
    if (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.signal) {
      requestOptions.signal.addEventListener("abort", () => {
        controller.abort();
      });
    }
    fetchOptions.signal = controller.signal;
  }
  return fetchOptions;
}
function addHelpers(response) {
  response.text = () => {
    if (response.candidates && response.candidates.length > 0) {
      if (response.candidates.length > 1) {
        console.warn(`This response had ${response.candidates.length} candidates. Returning text from the first candidate only. Access response.candidates directly to use the other candidates.`);
      }
      if (hadBadFinishReason(response.candidates[0])) {
        throw new GoogleGenerativeAIResponseError(`${formatBlockErrorMessage(response)}`, response);
      }
      return getText(response);
    } else if (response.promptFeedback) {
      throw new GoogleGenerativeAIResponseError(`Text not available. ${formatBlockErrorMessage(response)}`, response);
    }
    return "";
  };
  response.functionCall = () => {
    if (response.candidates && response.candidates.length > 0) {
      if (response.candidates.length > 1) {
        console.warn(`This response had ${response.candidates.length} candidates. Returning function calls from the first candidate only. Access response.candidates directly to use the other candidates.`);
      }
      if (hadBadFinishReason(response.candidates[0])) {
        throw new GoogleGenerativeAIResponseError(`${formatBlockErrorMessage(response)}`, response);
      }
      console.warn(`response.functionCall() is deprecated. Use response.functionCalls() instead.`);
      return getFunctionCalls(response)[0];
    } else if (response.promptFeedback) {
      throw new GoogleGenerativeAIResponseError(`Function call not available. ${formatBlockErrorMessage(response)}`, response);
    }
    return void 0;
  };
  response.functionCalls = () => {
    if (response.candidates && response.candidates.length > 0) {
      if (response.candidates.length > 1) {
        console.warn(`This response had ${response.candidates.length} candidates. Returning function calls from the first candidate only. Access response.candidates directly to use the other candidates.`);
      }
      if (hadBadFinishReason(response.candidates[0])) {
        throw new GoogleGenerativeAIResponseError(`${formatBlockErrorMessage(response)}`, response);
      }
      return getFunctionCalls(response);
    } else if (response.promptFeedback) {
      throw new GoogleGenerativeAIResponseError(`Function call not available. ${formatBlockErrorMessage(response)}`, response);
    }
    return void 0;
  };
  return response;
}
function getText(response) {
  var _a, _b, _c, _d;
  const textStrings = [];
  if ((_b = (_a = response.candidates) === null || _a === void 0 ? void 0 : _a[0].content) === null || _b === void 0 ? void 0 : _b.parts) {
    for (const part of (_d = (_c = response.candidates) === null || _c === void 0 ? void 0 : _c[0].content) === null || _d === void 0 ? void 0 : _d.parts) {
      if (part.text) {
        textStrings.push(part.text);
      }
      if (part.executableCode) {
        textStrings.push("\n```" + part.executableCode.language + "\n" + part.executableCode.code + "\n```\n");
      }
      if (part.codeExecutionResult) {
        textStrings.push("\n```\n" + part.codeExecutionResult.output + "\n```\n");
      }
    }
  }
  if (textStrings.length > 0) {
    return textStrings.join("");
  } else {
    return "";
  }
}
function getFunctionCalls(response) {
  var _a, _b, _c, _d;
  const functionCalls = [];
  if ((_b = (_a = response.candidates) === null || _a === void 0 ? void 0 : _a[0].content) === null || _b === void 0 ? void 0 : _b.parts) {
    for (const part of (_d = (_c = response.candidates) === null || _c === void 0 ? void 0 : _c[0].content) === null || _d === void 0 ? void 0 : _d.parts) {
      if (part.functionCall) {
        functionCalls.push(part.functionCall);
      }
    }
  }
  if (functionCalls.length > 0) {
    return functionCalls;
  } else {
    return void 0;
  }
}
var badFinishReasons = [
  FinishReason.RECITATION,
  FinishReason.SAFETY,
  FinishReason.LANGUAGE
];
function hadBadFinishReason(candidate) {
  return !!candidate.finishReason && badFinishReasons.includes(candidate.finishReason);
}
function formatBlockErrorMessage(response) {
  var _a, _b, _c;
  let message = "";
  if ((!response.candidates || response.candidates.length === 0) && response.promptFeedback) {
    message += "Response was blocked";
    if ((_a = response.promptFeedback) === null || _a === void 0 ? void 0 : _a.blockReason) {
      message += ` due to ${response.promptFeedback.blockReason}`;
    }
    if ((_b = response.promptFeedback) === null || _b === void 0 ? void 0 : _b.blockReasonMessage) {
      message += `: ${response.promptFeedback.blockReasonMessage}`;
    }
  } else if ((_c = response.candidates) === null || _c === void 0 ? void 0 : _c[0]) {
    const firstCandidate = response.candidates[0];
    if (hadBadFinishReason(firstCandidate)) {
      message += `Candidate was blocked due to ${firstCandidate.finishReason}`;
      if (firstCandidate.finishMessage) {
        message += `: ${firstCandidate.finishMessage}`;
      }
    }
  }
  return message;
}
function __await(v) {
  return this instanceof __await ? (this.v = v, this) : new __await(v);
}
function __asyncGenerator(thisArg, _arguments, generator) {
  if (!Symbol.asyncIterator)
    throw new TypeError("Symbol.asyncIterator is not defined.");
  var g = generator.apply(thisArg, _arguments || []), i, q = [];
  return i = {}, verb("next"), verb("throw"), verb("return"), i[Symbol.asyncIterator] = function() {
    return this;
  }, i;
  function verb(n) {
    if (g[n])
      i[n] = function(v) {
        return new Promise(function(a, b) {
          q.push([n, v, a, b]) > 1 || resume(n, v);
        });
      };
  }
  function resume(n, v) {
    try {
      step(g[n](v));
    } catch (e) {
      settle(q[0][3], e);
    }
  }
  function step(r) {
    r.value instanceof __await ? Promise.resolve(r.value.v).then(fulfill, reject) : settle(q[0][2], r);
  }
  function fulfill(value) {
    resume("next", value);
  }
  function reject(value) {
    resume("throw", value);
  }
  function settle(f, v) {
    if (f(v), q.shift(), q.length)
      resume(q[0][0], q[0][1]);
  }
}
var responseLineRE = /^data\: (.*)(?:\n\n|\r\r|\r\n\r\n)/;
function processStream(response) {
  const inputStream = response.body.pipeThrough(new TextDecoderStream("utf8", { fatal: true }));
  const responseStream = getResponseStream(inputStream);
  const [stream1, stream2] = responseStream.tee();
  return {
    stream: generateResponseSequence(stream1),
    response: getResponsePromise(stream2)
  };
}
async function getResponsePromise(stream) {
  const allResponses = [];
  const reader = stream.getReader();
  while (true) {
    const { done, value } = await reader.read();
    if (done) {
      return addHelpers(aggregateResponses(allResponses));
    }
    allResponses.push(value);
  }
}
function generateResponseSequence(stream) {
  return __asyncGenerator(this, arguments, function* generateResponseSequence_1() {
    const reader = stream.getReader();
    while (true) {
      const { value, done } = yield __await(reader.read());
      if (done) {
        break;
      }
      yield yield __await(addHelpers(value));
    }
  });
}
function getResponseStream(inputStream) {
  const reader = inputStream.getReader();
  const stream = new ReadableStream({
    start(controller) {
      let currentText = "";
      return pump();
      function pump() {
        return reader.read().then(({ value, done }) => {
          if (done) {
            if (currentText.trim()) {
              controller.error(new GoogleGenerativeAIError("Failed to parse stream"));
              return;
            }
            controller.close();
            return;
          }
          currentText += value;
          let match = currentText.match(responseLineRE);
          let parsedResponse;
          while (match) {
            try {
              parsedResponse = JSON.parse(match[1]);
            } catch (e) {
              controller.error(new GoogleGenerativeAIError(`Error parsing JSON response: "${match[1]}"`));
              return;
            }
            controller.enqueue(parsedResponse);
            currentText = currentText.substring(match[0].length);
            match = currentText.match(responseLineRE);
          }
          return pump();
        });
      }
    }
  });
  return stream;
}
function aggregateResponses(responses) {
  const lastResponse = responses[responses.length - 1];
  const aggregatedResponse = {
    promptFeedback: lastResponse === null || lastResponse === void 0 ? void 0 : lastResponse.promptFeedback
  };
  for (const response of responses) {
    if (response.candidates) {
      for (const candidate of response.candidates) {
        const i = candidate.index;
        if (!aggregatedResponse.candidates) {
          aggregatedResponse.candidates = [];
        }
        if (!aggregatedResponse.candidates[i]) {
          aggregatedResponse.candidates[i] = {
            index: candidate.index
          };
        }
        aggregatedResponse.candidates[i].citationMetadata = candidate.citationMetadata;
        aggregatedResponse.candidates[i].groundingMetadata = candidate.groundingMetadata;
        aggregatedResponse.candidates[i].finishReason = candidate.finishReason;
        aggregatedResponse.candidates[i].finishMessage = candidate.finishMessage;
        aggregatedResponse.candidates[i].safetyRatings = candidate.safetyRatings;
        if (candidate.content && candidate.content.parts) {
          if (!aggregatedResponse.candidates[i].content) {
            aggregatedResponse.candidates[i].content = {
              role: candidate.content.role || "user",
              parts: []
            };
          }
          const newPart = {};
          for (const part of candidate.content.parts) {
            if (part.text) {
              newPart.text = part.text;
            }
            if (part.functionCall) {
              newPart.functionCall = part.functionCall;
            }
            if (part.executableCode) {
              newPart.executableCode = part.executableCode;
            }
            if (part.codeExecutionResult) {
              newPart.codeExecutionResult = part.codeExecutionResult;
            }
            if (Object.keys(newPart).length === 0) {
              newPart.text = "";
            }
            aggregatedResponse.candidates[i].content.parts.push(newPart);
          }
        }
      }
    }
    if (response.usageMetadata) {
      aggregatedResponse.usageMetadata = response.usageMetadata;
    }
  }
  return aggregatedResponse;
}
async function generateContentStream(apiKey, model, params, requestOptions) {
  const response = await makeModelRequest(
    model,
    Task.STREAM_GENERATE_CONTENT,
    apiKey,
    /* stream */
    true,
    JSON.stringify(params),
    requestOptions
  );
  return processStream(response);
}
async function generateContent(apiKey, model, params, requestOptions) {
  const response = await makeModelRequest(
    model,
    Task.GENERATE_CONTENT,
    apiKey,
    /* stream */
    false,
    JSON.stringify(params),
    requestOptions
  );
  const responseJson = await response.json();
  const enhancedResponse = addHelpers(responseJson);
  return {
    response: enhancedResponse
  };
}
function formatSystemInstruction(input) {
  if (input == null) {
    return void 0;
  } else if (typeof input === "string") {
    return { role: "system", parts: [{ text: input }] };
  } else if (input.text) {
    return { role: "system", parts: [input] };
  } else if (input.parts) {
    if (!input.role) {
      return { role: "system", parts: input.parts };
    } else {
      return input;
    }
  }
}
function formatNewContent(request) {
  let newParts = [];
  if (typeof request === "string") {
    newParts = [{ text: request }];
  } else {
    for (const partOrString of request) {
      if (typeof partOrString === "string") {
        newParts.push({ text: partOrString });
      } else {
        newParts.push(partOrString);
      }
    }
  }
  return assignRoleToPartsAndValidateSendMessageRequest(newParts);
}
function assignRoleToPartsAndValidateSendMessageRequest(parts) {
  const userContent = { role: "user", parts: [] };
  const functionContent = { role: "function", parts: [] };
  let hasUserContent = false;
  let hasFunctionContent = false;
  for (const part of parts) {
    if ("functionResponse" in part) {
      functionContent.parts.push(part);
      hasFunctionContent = true;
    } else {
      userContent.parts.push(part);
      hasUserContent = true;
    }
  }
  if (hasUserContent && hasFunctionContent) {
    throw new GoogleGenerativeAIError("Within a single message, FunctionResponse cannot be mixed with other type of part in the request for sending chat message.");
  }
  if (!hasUserContent && !hasFunctionContent) {
    throw new GoogleGenerativeAIError("No content is provided for sending chat message.");
  }
  if (hasUserContent) {
    return userContent;
  }
  return functionContent;
}
function formatCountTokensInput(params, modelParams) {
  var _a;
  let formattedGenerateContentRequest = {
    model: modelParams === null || modelParams === void 0 ? void 0 : modelParams.model,
    generationConfig: modelParams === null || modelParams === void 0 ? void 0 : modelParams.generationConfig,
    safetySettings: modelParams === null || modelParams === void 0 ? void 0 : modelParams.safetySettings,
    tools: modelParams === null || modelParams === void 0 ? void 0 : modelParams.tools,
    toolConfig: modelParams === null || modelParams === void 0 ? void 0 : modelParams.toolConfig,
    systemInstruction: modelParams === null || modelParams === void 0 ? void 0 : modelParams.systemInstruction,
    cachedContent: (_a = modelParams === null || modelParams === void 0 ? void 0 : modelParams.cachedContent) === null || _a === void 0 ? void 0 : _a.name,
    contents: []
  };
  const containsGenerateContentRequest = params.generateContentRequest != null;
  if (params.contents) {
    if (containsGenerateContentRequest) {
      throw new GoogleGenerativeAIRequestInputError("CountTokensRequest must have one of contents or generateContentRequest, not both.");
    }
    formattedGenerateContentRequest.contents = params.contents;
  } else if (containsGenerateContentRequest) {
    formattedGenerateContentRequest = Object.assign(Object.assign({}, formattedGenerateContentRequest), params.generateContentRequest);
  } else {
    const content = formatNewContent(params);
    formattedGenerateContentRequest.contents = [content];
  }
  return { generateContentRequest: formattedGenerateContentRequest };
}
function formatGenerateContentInput(params) {
  let formattedRequest;
  if (params.contents) {
    formattedRequest = params;
  } else {
    const content = formatNewContent(params);
    formattedRequest = { contents: [content] };
  }
  if (params.systemInstruction) {
    formattedRequest.systemInstruction = formatSystemInstruction(params.systemInstruction);
  }
  return formattedRequest;
}
function formatEmbedContentInput(params) {
  if (typeof params === "string" || Array.isArray(params)) {
    const content = formatNewContent(params);
    return { content };
  }
  return params;
}
var VALID_PART_FIELDS = [
  "text",
  "inlineData",
  "functionCall",
  "functionResponse",
  "executableCode",
  "codeExecutionResult"
];
var VALID_PARTS_PER_ROLE = {
  user: ["text", "inlineData"],
  function: ["functionResponse"],
  model: ["text", "functionCall", "executableCode", "codeExecutionResult"],
  // System instructions shouldn't be in history anyway.
  system: ["text"]
};
function validateChatHistory(history) {
  let prevContent = false;
  for (const currContent of history) {
    const { role, parts } = currContent;
    if (!prevContent && role !== "user") {
      throw new GoogleGenerativeAIError(`First content should be with role 'user', got ${role}`);
    }
    if (!POSSIBLE_ROLES.includes(role)) {
      throw new GoogleGenerativeAIError(`Each item should include role field. Got ${role} but valid roles are: ${JSON.stringify(POSSIBLE_ROLES)}`);
    }
    if (!Array.isArray(parts)) {
      throw new GoogleGenerativeAIError("Content should have 'parts' property with an array of Parts");
    }
    if (parts.length === 0) {
      throw new GoogleGenerativeAIError("Each Content should have at least one part");
    }
    const countFields = {
      text: 0,
      inlineData: 0,
      functionCall: 0,
      functionResponse: 0,
      fileData: 0,
      executableCode: 0,
      codeExecutionResult: 0
    };
    for (const part of parts) {
      for (const key of VALID_PART_FIELDS) {
        if (key in part) {
          countFields[key] += 1;
        }
      }
    }
    const validParts = VALID_PARTS_PER_ROLE[role];
    for (const key of VALID_PART_FIELDS) {
      if (!validParts.includes(key) && countFields[key] > 0) {
        throw new GoogleGenerativeAIError(`Content with role '${role}' can't contain '${key}' part`);
      }
    }
    prevContent = true;
  }
}
var SILENT_ERROR = "SILENT_ERROR";
var ChatSession = class {
  constructor(apiKey, model, params, _requestOptions = {}) {
    this.model = model;
    this.params = params;
    this._requestOptions = _requestOptions;
    this._history = [];
    this._sendPromise = Promise.resolve();
    this._apiKey = apiKey;
    if (params === null || params === void 0 ? void 0 : params.history) {
      validateChatHistory(params.history);
      this._history = params.history;
    }
  }
  /**
   * Gets the chat history so far. Blocked prompts are not added to history.
   * Blocked candidates are not added to history, nor are the prompts that
   * generated them.
   */
  async getHistory() {
    await this._sendPromise;
    return this._history;
  }
  /**
   * Sends a chat message and receives a non-streaming
   * {@link GenerateContentResult}.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async sendMessage(request, requestOptions = {}) {
    var _a, _b, _c, _d, _e, _f;
    await this._sendPromise;
    const newContent = formatNewContent(request);
    const generateContentRequest = {
      safetySettings: (_a = this.params) === null || _a === void 0 ? void 0 : _a.safetySettings,
      generationConfig: (_b = this.params) === null || _b === void 0 ? void 0 : _b.generationConfig,
      tools: (_c = this.params) === null || _c === void 0 ? void 0 : _c.tools,
      toolConfig: (_d = this.params) === null || _d === void 0 ? void 0 : _d.toolConfig,
      systemInstruction: (_e = this.params) === null || _e === void 0 ? void 0 : _e.systemInstruction,
      cachedContent: (_f = this.params) === null || _f === void 0 ? void 0 : _f.cachedContent,
      contents: [...this._history, newContent]
    };
    const chatSessionRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    let finalResult;
    this._sendPromise = this._sendPromise.then(() => generateContent(this._apiKey, this.model, generateContentRequest, chatSessionRequestOptions)).then((result) => {
      var _a2;
      if (result.response.candidates && result.response.candidates.length > 0) {
        this._history.push(newContent);
        const responseContent = Object.assign({
          parts: [],
          // Response seems to come back without a role set.
          role: "model"
        }, (_a2 = result.response.candidates) === null || _a2 === void 0 ? void 0 : _a2[0].content);
        this._history.push(responseContent);
      } else {
        const blockErrorMessage = formatBlockErrorMessage(result.response);
        if (blockErrorMessage) {
          console.warn(`sendMessage() was unsuccessful. ${blockErrorMessage}. Inspect response object for details.`);
        }
      }
      finalResult = result;
    });
    await this._sendPromise;
    return finalResult;
  }
  /**
   * Sends a chat message and receives the response as a
   * {@link GenerateContentStreamResult} containing an iterable stream
   * and a response promise.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async sendMessageStream(request, requestOptions = {}) {
    var _a, _b, _c, _d, _e, _f;
    await this._sendPromise;
    const newContent = formatNewContent(request);
    const generateContentRequest = {
      safetySettings: (_a = this.params) === null || _a === void 0 ? void 0 : _a.safetySettings,
      generationConfig: (_b = this.params) === null || _b === void 0 ? void 0 : _b.generationConfig,
      tools: (_c = this.params) === null || _c === void 0 ? void 0 : _c.tools,
      toolConfig: (_d = this.params) === null || _d === void 0 ? void 0 : _d.toolConfig,
      systemInstruction: (_e = this.params) === null || _e === void 0 ? void 0 : _e.systemInstruction,
      cachedContent: (_f = this.params) === null || _f === void 0 ? void 0 : _f.cachedContent,
      contents: [...this._history, newContent]
    };
    const chatSessionRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    const streamPromise = generateContentStream(this._apiKey, this.model, generateContentRequest, chatSessionRequestOptions);
    this._sendPromise = this._sendPromise.then(() => streamPromise).catch((_ignored) => {
      throw new Error(SILENT_ERROR);
    }).then((streamResult) => streamResult.response).then((response) => {
      if (response.candidates && response.candidates.length > 0) {
        this._history.push(newContent);
        const responseContent = Object.assign({}, response.candidates[0].content);
        if (!responseContent.role) {
          responseContent.role = "model";
        }
        this._history.push(responseContent);
      } else {
        const blockErrorMessage = formatBlockErrorMessage(response);
        if (blockErrorMessage) {
          console.warn(`sendMessageStream() was unsuccessful. ${blockErrorMessage}. Inspect response object for details.`);
        }
      }
    }).catch((e) => {
      if (e.message !== SILENT_ERROR) {
        console.error(e);
      }
    });
    return streamPromise;
  }
};
async function countTokens(apiKey, model, params, singleRequestOptions) {
  const response = await makeModelRequest(model, Task.COUNT_TOKENS, apiKey, false, JSON.stringify(params), singleRequestOptions);
  return response.json();
}
async function embedContent(apiKey, model, params, requestOptions) {
  const response = await makeModelRequest(model, Task.EMBED_CONTENT, apiKey, false, JSON.stringify(params), requestOptions);
  return response.json();
}
async function batchEmbedContents(apiKey, model, params, requestOptions) {
  const requestsWithModel = params.requests.map((request) => {
    return Object.assign(Object.assign({}, request), { model });
  });
  const response = await makeModelRequest(model, Task.BATCH_EMBED_CONTENTS, apiKey, false, JSON.stringify({ requests: requestsWithModel }), requestOptions);
  return response.json();
}
var GenerativeModel = class {
  constructor(apiKey, modelParams, _requestOptions = {}) {
    this.apiKey = apiKey;
    this._requestOptions = _requestOptions;
    if (modelParams.model.includes("/")) {
      this.model = modelParams.model;
    } else {
      this.model = `models/${modelParams.model}`;
    }
    this.generationConfig = modelParams.generationConfig || {};
    this.safetySettings = modelParams.safetySettings || [];
    this.tools = modelParams.tools;
    this.toolConfig = modelParams.toolConfig;
    this.systemInstruction = formatSystemInstruction(modelParams.systemInstruction);
    this.cachedContent = modelParams.cachedContent;
  }
  /**
   * Makes a single non-streaming call to the model
   * and returns an object containing a single {@link GenerateContentResponse}.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async generateContent(request, requestOptions = {}) {
    var _a;
    const formattedParams = formatGenerateContentInput(request);
    const generativeModelRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    return generateContent(this.apiKey, this.model, Object.assign({ generationConfig: this.generationConfig, safetySettings: this.safetySettings, tools: this.tools, toolConfig: this.toolConfig, systemInstruction: this.systemInstruction, cachedContent: (_a = this.cachedContent) === null || _a === void 0 ? void 0 : _a.name }, formattedParams), generativeModelRequestOptions);
  }
  /**
   * Makes a single streaming call to the model and returns an object
   * containing an iterable stream that iterates over all chunks in the
   * streaming response as well as a promise that returns the final
   * aggregated response.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async generateContentStream(request, requestOptions = {}) {
    var _a;
    const formattedParams = formatGenerateContentInput(request);
    const generativeModelRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    return generateContentStream(this.apiKey, this.model, Object.assign({ generationConfig: this.generationConfig, safetySettings: this.safetySettings, tools: this.tools, toolConfig: this.toolConfig, systemInstruction: this.systemInstruction, cachedContent: (_a = this.cachedContent) === null || _a === void 0 ? void 0 : _a.name }, formattedParams), generativeModelRequestOptions);
  }
  /**
   * Gets a new {@link ChatSession} instance which can be used for
   * multi-turn chats.
   */
  startChat(startChatParams) {
    var _a;
    return new ChatSession(this.apiKey, this.model, Object.assign({ generationConfig: this.generationConfig, safetySettings: this.safetySettings, tools: this.tools, toolConfig: this.toolConfig, systemInstruction: this.systemInstruction, cachedContent: (_a = this.cachedContent) === null || _a === void 0 ? void 0 : _a.name }, startChatParams), this._requestOptions);
  }
  /**
   * Counts the tokens in the provided request.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async countTokens(request, requestOptions = {}) {
    const formattedParams = formatCountTokensInput(request, {
      model: this.model,
      generationConfig: this.generationConfig,
      safetySettings: this.safetySettings,
      tools: this.tools,
      toolConfig: this.toolConfig,
      systemInstruction: this.systemInstruction,
      cachedContent: this.cachedContent
    });
    const generativeModelRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    return countTokens(this.apiKey, this.model, formattedParams, generativeModelRequestOptions);
  }
  /**
   * Embeds the provided content.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async embedContent(request, requestOptions = {}) {
    const formattedParams = formatEmbedContentInput(request);
    const generativeModelRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    return embedContent(this.apiKey, this.model, formattedParams, generativeModelRequestOptions);
  }
  /**
   * Embeds an array of {@link EmbedContentRequest}s.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async batchEmbedContents(batchEmbedContentRequest, requestOptions = {}) {
    const generativeModelRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    return batchEmbedContents(this.apiKey, this.model, batchEmbedContentRequest, generativeModelRequestOptions);
  }
};
var GoogleGenerativeAI = class {
  constructor(apiKey) {
    this.apiKey = apiKey;
  }
  /**
   * Gets a {@link GenerativeModel} instance for the provided model name.
   */
  getGenerativeModel(modelParams, requestOptions) {
    if (!modelParams.model) {
      throw new GoogleGenerativeAIError(`Must provide a model name. Example: genai.getGenerativeModel({ model: 'my-model-name' })`);
    }
    return new GenerativeModel(this.apiKey, modelParams, requestOptions);
  }
  /**
   * Creates a {@link GenerativeModel} instance from provided content cache.
   */
  getGenerativeModelFromCachedContent(cachedContent, modelParams, requestOptions) {
    if (!cachedContent.name) {
      throw new GoogleGenerativeAIRequestInputError("Cached content must contain a `name` field.");
    }
    if (!cachedContent.model) {
      throw new GoogleGenerativeAIRequestInputError("Cached content must contain a `model` field.");
    }
    const disallowedDuplicates = ["model", "systemInstruction"];
    for (const key of disallowedDuplicates) {
      if ((modelParams === null || modelParams === void 0 ? void 0 : modelParams[key]) && cachedContent[key] && (modelParams === null || modelParams === void 0 ? void 0 : modelParams[key]) !== cachedContent[key]) {
        if (key === "model") {
          const modelParamsComp = modelParams.model.startsWith("models/") ? modelParams.model.replace("models/", "") : modelParams.model;
          const cachedContentComp = cachedContent.model.startsWith("models/") ? cachedContent.model.replace("models/", "") : cachedContent.model;
          if (modelParamsComp === cachedContentComp) {
            continue;
          }
        }
        throw new GoogleGenerativeAIRequestInputError(`Different value for "${key}" specified in modelParams (${modelParams[key]}) and cachedContent (${cachedContent[key]})`);
      }
    }
    const modelParamsFromCache = Object.assign(Object.assign({}, modelParams), { model: cachedContent.model, tools: cachedContent.tools, toolConfig: cachedContent.toolConfig, systemInstruction: cachedContent.systemInstruction, cachedContent });
    return new GenerativeModel(this.apiKey, modelParamsFromCache, requestOptions);
  }
};

// src/gemini-service.ts
var import_obsidian2 = require("obsidian");
var API_BASE_URL = "https://generativelanguage.googleapis.com/v1beta";
var UPLOAD_BASE_URL = "https://generativelanguage.googleapis.com/upload/v1beta";
var GeminiService = class {
  constructor(plugin) {
    this.genAI = null;
    this.model = null;
    this.chatHistory = [];
    this.plugin = plugin;
    this.initializeClient();
  }
  initializeClient() {
    if (this.plugin.settings.apiKey) {
      this.genAI = new GoogleGenerativeAI(this.plugin.settings.apiKey);
      this.model = this.genAI.getGenerativeModel({ model: this.plugin.settings.model });
    }
  }
  refreshClient() {
    this.initializeClient();
  }
  // Helper method to make API requests using Obsidian's requestUrl (bypasses CORS)
  async apiRequest(url, method = "GET", body) {
    try {
      console.log(`[Gemini API] Request: ${method} ${url}`);
      const params = {
        url,
        method,
        headers: { "Content-Type": "application/json" }
      };
      if (body) {
        params.body = JSON.stringify(body);
      }
      const response = await (0, import_obsidian2.requestUrl)(params);
      return {
        ok: response.status >= 200 && response.status < 300,
        status: response.status,
        data: response.json
      };
    } catch (error) {
      console.error("API request error:", error);
      if (error.response) {
        return {
          ok: false,
          status: error.status || 500,
          data: error.response
        };
      }
      return {
        ok: false,
        status: 500,
        data: { error: error.message }
      };
    }
  }
  async verifyApiKey() {
    try {
      if (!this.plugin.settings.apiKey)
        return false;
      const response = await this.apiRequest(
        `${API_BASE_URL}/models?key=${this.plugin.settings.apiKey}`
      );
      return response.ok;
    } catch (error) {
      console.error("API key verification failed:", error);
      return false;
    }
  }
  // ==================== Corpus Management (FileSearchStores) ====================
  async createCorpus(displayName) {
    try {
      const response = await this.apiRequest(
        `${API_BASE_URL}/fileSearchStores?key=${this.plugin.settings.apiKey}`,
        "POST",
        { displayName }
      );
      if (!response.ok) {
        console.error("Failed to create fileSearchStore:", response.data);
        return null;
      }
      return response.data;
    } catch (error) {
      console.error("Create fileSearchStore error:", error);
      return null;
    }
  }
  async listCorpora() {
    try {
      const response = await this.apiRequest(
        `${API_BASE_URL}/fileSearchStores?key=${this.plugin.settings.apiKey}`
      );
      if (!response.ok) {
        console.error("Failed to list fileSearchStores");
        return [];
      }
      return response.data.fileSearchStores || [];
    } catch (error) {
      console.error("List fileSearchStores error:", error);
      return [];
    }
  }
  async getOrCreateCorpus() {
    if (this.plugin.settings.corpusName && this.plugin.settings.corpusName.startsWith("corpora/")) {
      console.log("Migrating from legacy corpus to fileSearchStore...");
      this.plugin.settings.corpusName = "";
      await this.plugin.saveSettings();
    }
    if (this.plugin.settings.corpusName) {
      console.log(`Verifying corpus: ${this.plugin.settings.corpusName}`);
      try {
        const response = await this.apiRequest(
          `${API_BASE_URL}/${this.plugin.settings.corpusName}?key=${this.plugin.settings.apiKey}`
        );
        if (response.ok) {
          console.log("Corpus verified.");
          return this.plugin.settings.corpusName;
        } else if (response.status === 404) {
          console.warn("Corpus not found (404), clearing setting to recreate.");
          this.plugin.settings.corpusName = "";
          await this.plugin.saveSettings();
        } else {
          console.error("Error verifying corpus:", response.data);
        }
      } catch (error) {
        console.error("Error checking corpus existence:", error);
      }
    }
    const corpora = await this.listCorpora();
    const existing = corpora.find(
      (c) => c.displayName === this.plugin.settings.corpusDisplayName
    );
    if (existing) {
      console.log(`Found existing corpus: ${existing.name}`);
      this.plugin.settings.corpusName = existing.name;
      await this.plugin.saveSettings();
      return existing.name;
    }
    console.log(`Creating new corpus: ${this.plugin.settings.corpusDisplayName}`);
    const newCorpus = await this.createCorpus(this.plugin.settings.corpusDisplayName);
    if (newCorpus) {
      this.plugin.settings.corpusName = newCorpus.name;
      await this.plugin.saveSettings();
      return newCorpus.name;
    }
    return null;
  }
  // ==================== Document Management ====================
  // Helper method for multipart upload to File Search Store
  async uploadToFileSearchStore(fileSearchStoreName, displayName, content, mimeType = "text/markdown") {
    try {
      const boundary = "----WebKitFormBoundary" + Math.random().toString(36).substring(2);
      const metadata = JSON.stringify({
        displayName,
        customMetadata: [
          { key: "path", stringValue: displayName },
          { key: "source", stringValue: "obsidian" }
        ]
      });
      let body = "";
      body += `--${boundary}\r
`;
      body += "Content-Type: application/json; charset=UTF-8\r\n\r\n";
      body += metadata + "\r\n";
      body += `--${boundary}\r
`;
      body += `Content-Type: ${mimeType}\r
\r
`;
      body += content + "\r\n";
      body += `--${boundary}--`;
      const url = `${UPLOAD_BASE_URL}/${fileSearchStoreName}:uploadToFileSearchStore?key=${this.plugin.settings.apiKey}`;
      console.log(`[Gemini API] Upload to FileSearchStore: ${url}`);
      const response = await (0, import_obsidian2.requestUrl)({
        url,
        method: "POST",
        headers: {
          "Content-Type": `multipart/related; boundary=${boundary}`
        },
        body
      });
      return {
        ok: response.status >= 200 && response.status < 300,
        status: response.status,
        data: response.json
      };
    } catch (error) {
      console.error("Upload to FileSearchStore error:", error);
      if (error.response) {
        return {
          ok: false,
          status: error.status || 500,
          data: error.response
        };
      }
      return {
        ok: false,
        status: 500,
        data: { error: error.message }
      };
    }
  }
  async uploadDocument(corpusName, filePath, content) {
    try {
      console.log(`[Gemini API] Uploading document: ${filePath} to ${corpusName}`);
      const response = await this.uploadToFileSearchStore(
        corpusName,
        filePath,
        content,
        "text/markdown"
      );
      if (!response.ok) {
        console.error("Failed to upload document:", response.data);
        return null;
      }
      const result = response.data;
      if (result.name && result.name.includes("/documents/")) {
        return {
          name: result.name,
          displayName: result.displayName || filePath,
          createTime: result.createTime || new Date().toISOString(),
          updateTime: result.updateTime || new Date().toISOString()
        };
      }
      if (result.metadata && result.metadata.document) {
        return {
          name: result.metadata.document,
          displayName: filePath,
          createTime: new Date().toISOString(),
          updateTime: new Date().toISOString()
        };
      }
      console.log("[Gemini API] Upload response:", result);
      return result;
    } catch (error) {
      console.error("Upload document error:", error);
      return null;
    }
  }
  async updateDocument(documentName, content) {
    try {
      console.log(`[Gemini API] Updating document: ${documentName}`);
      const parts = documentName.split("/");
      if (parts.length < 4) {
        console.error("Invalid document name format:", documentName);
        return false;
      }
      const fileSearchStoreName = `${parts[0]}/${parts[1]}`;
      const getResponse = await this.apiRequest(
        `${API_BASE_URL}/${documentName}?key=${this.plugin.settings.apiKey}`
      );
      let displayName = "unknown.md";
      if (getResponse.ok && getResponse.data.displayName) {
        displayName = getResponse.data.displayName;
      }
      const deleteSuccess = await this.deleteDocument(documentName);
      if (!deleteSuccess) {
        console.error("Failed to delete old document for update");
        return false;
      }
      const uploadResponse = await this.uploadToFileSearchStore(
        fileSearchStoreName,
        displayName,
        content,
        "text/markdown"
      );
      return uploadResponse.ok;
    } catch (error) {
      console.error("Update document error:", error);
      return false;
    }
  }
  async deleteDocument(documentName) {
    try {
      const response = await this.apiRequest(
        `${API_BASE_URL}/${documentName}?key=${this.plugin.settings.apiKey}`,
        "DELETE"
      );
      return response.ok;
    } catch (error) {
      console.error("Delete document error:", error);
      return false;
    }
  }
  async listDocuments(corpusName) {
    try {
      const response = await this.apiRequest(
        `${API_BASE_URL}/${corpusName}/documents?key=${this.plugin.settings.apiKey}`
      );
      if (!response.ok) {
        console.error("Failed to list documents");
        return [];
      }
      return response.data.documents || [];
    } catch (error) {
      console.error("List documents error:", error);
      return [];
    }
  }
  // ==================== Chat / RAG ====================
  async chat(userMessage) {
    if (!this.model) {
      this.initializeClient();
    }
    if (!this.model) {
      return {
        role: "model",
        content: "Error: Gemini API not configured. Please set your API key in settings."
      };
    }
    try {
      const context = await this.buildContext();
      const systemPrompt = `You are a helpful assistant that answers questions based on the user's personal notes from their Obsidian vault.

Here are the relevant notes for context:

${context}

Instructions:
1. Answer questions based primarily on the provided notes.
2. When referencing information from a note, cite it using the format [Source: filename.md].
3. If the information is not in the notes, you can provide general knowledge but clearly state that it's not from the notes.
4. Be concise and helpful.`;
      this.chatHistory.push({
        role: "user",
        parts: [{ text: userMessage }]
      });
      const chat = this.model.startChat({
        history: [
          {
            role: "user",
            parts: [{ text: systemPrompt }]
          },
          {
            role: "model",
            parts: [{ text: "I understand. I will help answer questions based on your Obsidian notes and cite sources when referencing specific information." }]
          },
          ...this.chatHistory.slice(0, -1)
          // Previous history without current message
        ]
      });
      const result = await chat.sendMessage(userMessage);
      const response = await result.response;
      const text = response.text();
      this.chatHistory.push({
        role: "model",
        parts: [{ text }]
      });
      const citations = this.extractCitations(text);
      return {
        role: "model",
        content: text,
        citations
      };
    } catch (error) {
      console.error("Chat error:", error);
      return {
        role: "model",
        content: `Error: ${error instanceof Error ? error.message : "Unknown error occurred"}`
      };
    }
  }
  async buildContext() {
    const files = this.plugin.settings.files;
    const contexts = [];
    for (const path in files) {
      if (files[path].status === "synced") {
        try {
          const file = this.plugin.app.vault.getAbstractFileByPath(path);
          if (file && file instanceof import_obsidian2.TFile && file.extension === "md") {
            const content = await this.plugin.app.vault.read(file);
            const truncated = content.length > 2e3 ? content.substring(0, 2e3) + "...[truncated]" : content;
            contexts.push(`--- ${path} ---
${truncated}
`);
          }
        } catch (e) {
          console.error(`Failed to read file ${path}:`, e);
        }
      }
    }
    let totalContext = contexts.join("\n");
    if (totalContext.length > 3e4) {
      totalContext = totalContext.substring(0, 3e4) + "\n...[context truncated due to length]";
    }
    return totalContext || "No synced notes available.";
  }
  extractCitations(text) {
    const citations = [];
    const pattern = /\[Source:\s*([^\]]+)\]|\[\[([^\]]+)\]\]/g;
    let match;
    while ((match = pattern.exec(text)) !== null) {
      const sourcePath = match[1] || match[2];
      if (sourcePath && !citations.find((c) => c.sourcePath === sourcePath)) {
        citations.push({
          sourceId: sourcePath,
          sourcePath: sourcePath.trim(),
          content: ""
        });
      }
    }
    return citations;
  }
  clearChatHistory() {
    this.chatHistory = [];
  }
  // ==================== Semantic Retrieval (Alternative approach) ====================
  async queryCorpus(query) {
    if (!this.plugin.settings.corpusName) {
      return { results: [] };
    }
    try {
      const response = await this.apiRequest(
        `${API_BASE_URL}/${this.plugin.settings.corpusName}:query?key=${this.plugin.settings.apiKey}`,
        "POST",
        {
          query,
          resultsCount: 5
        }
      );
      if (!response.ok) {
        console.error("Query corpus failed");
        return { results: [] };
      }
      return response.data;
    } catch (error) {
      console.error("Query corpus error:", error);
      return { results: [] };
    }
  }
};

// src/sync-engine.ts
var import_obsidian3 = require("obsidian");
var SyncEngine = class {
  constructor(plugin, geminiService) {
    this.syncQueue = /* @__PURE__ */ new Map();
    this.isSyncing = false;
    this.plugin = plugin;
    this.geminiService = geminiService;
    this.debouncedProcessQueue = (0, import_obsidian3.debounce)(
      () => this.processQueue(),
      this.plugin.settings.syncDebounceMs,
      true
    );
  }
  // ==================== Hash Utilities ====================
  async calculateHash(content) {
    const encoder = new TextEncoder();
    const data = encoder.encode(content);
    const hashBuffer = await crypto.subtle.digest("SHA-256", data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
  }
  // ==================== File Event Handlers ====================
  async handleFileCreate(file) {
    if (!this.plugin.settings.autoSync)
      return;
    console.log(`[SyncEngine] File created: ${file.path}`);
    this.addToQueue(file);
  }
  async handleFileModify(file) {
    if (!this.plugin.settings.autoSync)
      return;
    console.log(`[SyncEngine] File modified: ${file.path}`);
    this.addToQueue(file);
  }
  async handleFileDelete(file) {
    console.log(`[SyncEngine] File deleted: ${file.path}`);
    const fileData = this.plugin.settings.files[file.path];
    if (fileData && fileData.uri) {
      this.plugin.updateStatusBar("Deleting...");
      const success = await this.geminiService.deleteDocument(fileData.uri);
      if (success) {
        delete this.plugin.settings.files[file.path];
        await this.plugin.saveSettings();
        console.log(`[SyncEngine] Successfully deleted from Gemini: ${file.path}`);
      } else {
        console.error(`[SyncEngine] Failed to delete from Gemini: ${file.path}`);
      }
      this.plugin.updateStatusBar("Ready");
    }
  }
  async handleFileRename(file, oldPath) {
    console.log(`[SyncEngine] File renamed: ${oldPath} -> ${file.path}`);
    const oldFileData = this.plugin.settings.files[oldPath];
    if (oldFileData && oldFileData.uri) {
      await this.geminiService.deleteDocument(oldFileData.uri);
      delete this.plugin.settings.files[oldPath];
    }
    if (this.plugin.shouldSync(file)) {
      this.addToQueue(file);
    }
    await this.plugin.saveSettings();
  }
  // ==================== Queue Management ====================
  addToQueue(file) {
    this.syncQueue.set(file.path, file);
    this.debouncedProcessQueue();
  }
  async processQueue() {
    if (this.isSyncing || this.syncQueue.size === 0)
      return;
    this.isSyncing = true;
    this.plugin.updateStatusBar(`Syncing (${this.syncQueue.size})...`);
    const corpusName = await this.geminiService.getOrCreateCorpus();
    if (!corpusName) {
      console.error("[SyncEngine] Failed to get/create corpus");
      new import_obsidian3.Notice("Failed to connect to Gemini. Check your API key.");
      this.isSyncing = false;
      this.plugin.updateStatusBar("Error");
      return;
    }
    const entries = Array.from(this.syncQueue.entries());
    this.syncQueue.clear();
    let successCount = 0;
    let errorCount = 0;
    for (const [path, file] of entries) {
      try {
        const success = await this.syncFile(file, corpusName);
        if (success) {
          successCount++;
        } else {
          errorCount++;
        }
      } catch (error) {
        console.error(`[SyncEngine] Error syncing ${path}:`, error);
        errorCount++;
      }
      await this.delay(200);
    }
    this.isSyncing = false;
    if (errorCount > 0) {
      this.plugin.updateStatusBar(`Done (${errorCount} errors)`);
      setTimeout(() => this.plugin.updateStatusBar("Ready"), 3e3);
    } else {
      this.plugin.updateStatusBar("Ready");
    }
    this.plugin.updateChatViewSyncStatus();
    console.log(`[SyncEngine] Queue processed: ${successCount} success, ${errorCount} errors`);
  }
  // ==================== File Sync Logic ====================
  async syncFile(file, corpusName) {
    try {
      const content = await this.plugin.app.vault.read(file);
      const newHash = await this.calculateHash(content);
      const existingData = this.plugin.settings.files[file.path];
      if (existingData && existingData.hash === newHash) {
        console.log(`[SyncEngine] Skipping ${file.path} - no changes`);
        return true;
      }
      if (existingData && existingData.uri) {
        console.log(`[SyncEngine] Updating ${file.path}`);
        const success = await this.geminiService.updateDocument(existingData.uri, content);
        if (success) {
          this.plugin.settings.files[file.path] = {
            ...existingData,
            hash: newHash,
            lastSynced: Date.now(),
            status: "synced"
          };
          await this.plugin.saveSettings();
          return true;
        } else {
          this.plugin.settings.files[file.path] = {
            ...existingData,
            status: "error"
          };
          await this.plugin.saveSettings();
          return false;
        }
      } else {
        console.log(`[SyncEngine] Uploading ${file.path}`);
        const document2 = await this.geminiService.uploadDocument(corpusName, file.path, content);
        if (document2) {
          this.plugin.settings.files[file.path] = {
            uri: document2.name,
            hash: newHash,
            lastSynced: Date.now(),
            status: "synced"
          };
          await this.plugin.saveSettings();
          return true;
        } else {
          this.plugin.settings.files[file.path] = {
            uri: "",
            hash: "",
            lastSynced: Date.now(),
            status: "error"
          };
          await this.plugin.saveSettings();
          return false;
        }
      }
    } catch (error) {
      console.error(`[SyncEngine] Error syncing ${file.path}:`, error);
      return false;
    }
  }
  // ==================== Bulk Sync Operations ====================
  async initialSync() {
    console.log("[SyncEngine] Starting initial sync...");
    if (!this.plugin.settings.syncFolder) {
      console.log("[SyncEngine] No sync folder configured");
      return;
    }
    const files = this.getFilesInSyncFolder();
    console.log(`[SyncEngine] Found ${files.length} files to check`);
    for (const file of files) {
      const existingData = this.plugin.settings.files[file.path];
      if (!existingData || existingData.status !== "synced") {
        this.addToQueue(file);
      }
    }
    for (const path in this.plugin.settings.files) {
      const file = this.plugin.app.vault.getAbstractFileByPath(path);
      if (!file) {
        console.log(`[SyncEngine] Removing orphaned entry: ${path}`);
        delete this.plugin.settings.files[path];
      }
    }
    await this.plugin.saveSettings();
  }
  async fullSync() {
    console.log("[SyncEngine] Starting full sync...");
    new import_obsidian3.Notice("Starting full sync...");
    if (!this.plugin.settings.syncFolder) {
      new import_obsidian3.Notice("Please configure a sync folder first");
      return;
    }
    const files = this.getFilesInSyncFolder();
    console.log(`[SyncEngine] Found ${files.length} files to sync`);
    for (const path in this.plugin.settings.files) {
      this.plugin.settings.files[path].status = "pending";
    }
    await this.plugin.saveSettings();
    for (const file of files) {
      this.syncQueue.set(file.path, file);
    }
    await this.processQueue();
    new import_obsidian3.Notice(`Sync complete: ${files.length} files processed`);
  }
  // ==================== Utilities ====================
  getFilesInSyncFolder() {
    const syncFolder = this.plugin.settings.syncFolder;
    if (!syncFolder)
      return [];
    const files = [];
    const allFiles = this.plugin.app.vault.getMarkdownFiles();
    for (const file of allFiles) {
      if (file.path.startsWith(syncFolder)) {
        files.push(file);
      }
    }
    return files;
  }
  delay(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  getStats() {
    const files = this.plugin.settings.files;
    let synced = 0;
    let pending = 0;
    let error = 0;
    for (const path in files) {
      const status = files[path].status;
      if (status === "synced")
        synced++;
      else if (status === "pending")
        pending++;
      else if (status === "error")
        error++;
    }
    return {
      total: Object.keys(files).length,
      synced,
      pending,
      error
    };
  }
};

// src/chat-view.ts
var import_obsidian4 = require("obsidian");
var CHAT_VIEW_TYPE = "gemini-chat-view";
var ChatView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.messages = [];
    this.isLoading = false;
    this.syncStatusEl = null;
    this.welcomeEl = null;
    this.plugin = plugin;
  }
  getViewType() {
    return CHAT_VIEW_TYPE;
  }
  getDisplayText() {
    return "Gemini Chat";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("gemini-chat-container");
    const header = container.createDiv({ cls: "gemini-chat-header" });
    header.createEl("h4", { text: "\u{1F4AC} Chat with your Notes" });
    const headerActions = header.createDiv({ cls: "gemini-chat-header-actions" });
    const clearBtn = headerActions.createEl("button", {
      cls: "gemini-chat-clear-btn",
      text: "\u{1F5D1}\uFE0F Clear"
    });
    clearBtn.addEventListener("click", () => this.clearChat());
    const stats = this.plugin.syncEngine.getStats();
    this.syncStatusEl = headerActions.createEl("span", {
      cls: "gemini-chat-sync-status",
      text: `\u{1F4DA} ${stats.synced} notes synced`
    });
    this.messagesContainer = container.createDiv({ cls: "gemini-chat-messages" });
    if (this.messages.length === 0) {
      this.showWelcomeMessage();
    } else {
      for (const msg of this.messages) {
        this.renderMessage(msg);
      }
    }
    this.inputContainer = container.createDiv({ cls: "gemini-chat-input-container" });
    this.inputEl = this.inputContainer.createEl("textarea", {
      cls: "gemini-chat-input",
      placeholder: "Ask about your notes..."
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });
    this.inputEl.addEventListener("input", () => {
      this.inputEl.style.height = "auto";
      this.inputEl.style.height = Math.min(this.inputEl.scrollHeight, 150) + "px";
    });
    this.sendButton = this.inputContainer.createEl("button", {
      cls: "gemini-chat-send-btn",
      text: "\u27A4"
    });
    this.sendButton.addEventListener("click", () => this.sendMessage());
  }
  async onClose() {
  }
  // Public method to update sync status - can be called from outside
  updateSyncStatus() {
    const stats = this.plugin.syncEngine.getStats();
    if (this.syncStatusEl) {
      this.syncStatusEl.textContent = `\u{1F4DA} ${stats.synced} notes synced`;
    }
    if (this.welcomeEl) {
      const existingWarning = this.welcomeEl.querySelector(".gemini-chat-welcome-warning");
      if (existingWarning) {
        existingWarning.remove();
      }
      if (stats.synced === 0) {
        const paragraphs = this.welcomeEl.querySelectorAll("p");
        if (paragraphs.length > 0) {
          const warningEl = this.welcomeEl.createEl("p", {
            cls: "gemini-chat-welcome-warning",
            text: "\u26A0\uFE0F No notes synced yet. Configure sync in settings to get started."
          });
          paragraphs[0].after(warningEl);
        }
      }
    }
  }
  showWelcomeMessage() {
    this.welcomeEl = this.messagesContainer.createDiv({ cls: "gemini-chat-welcome" });
    this.welcomeEl.createEl("div", { cls: "gemini-chat-welcome-icon", text: "\u{1F916}" });
    this.welcomeEl.createEl("h3", { text: "Welcome to Gemini Chat!" });
    this.welcomeEl.createEl("p", { text: "Ask questions about your synced notes. I'll help you find information and provide insights based on your personal knowledge base." });
    const stats = this.plugin.syncEngine.getStats();
    if (stats.synced === 0) {
      this.welcomeEl.createEl("p", {
        cls: "gemini-chat-welcome-warning",
        text: "\u26A0\uFE0F No notes synced yet. Configure sync in settings to get started."
      });
    }
    const examplesEl = this.welcomeEl.createDiv({ cls: "gemini-chat-examples" });
    examplesEl.createEl("p", { text: "Try asking:" });
    const examples = [
      "What are the main topics in my notes?",
      "Summarize my notes about [topic]",
      "Find connections between [topic A] and [topic B]"
    ];
    for (const example of examples) {
      const exampleBtn = examplesEl.createEl("button", {
        cls: "gemini-chat-example-btn",
        text: example
      });
      exampleBtn.addEventListener("click", () => {
        this.inputEl.value = example;
        this.inputEl.focus();
      });
    }
  }
  async sendMessage() {
    const text = this.inputEl.value.trim();
    if (!text || this.isLoading)
      return;
    if (!this.plugin.settings.apiKey) {
      new import_obsidian4.Notice("Please configure your Gemini API key in settings");
      return;
    }
    const welcomeEl = this.messagesContainer.querySelector(".gemini-chat-welcome");
    if (welcomeEl) {
      welcomeEl.remove();
    }
    const userMessage = {
      role: "user",
      content: text
    };
    this.messages.push(userMessage);
    this.renderMessage(userMessage);
    this.inputEl.value = "";
    this.inputEl.style.height = "auto";
    this.isLoading = true;
    this.sendButton.disabled = true;
    this.sendButton.textContent = "\u23F3";
    const loadingEl = this.messagesContainer.createDiv({ cls: "gemini-chat-loading" });
    loadingEl.createEl("span", { cls: "gemini-chat-loading-dots", text: "\u25CF\u25CF\u25CF" });
    this.scrollToBottom();
    try {
      const response = await this.plugin.geminiService.chat(text);
      loadingEl.remove();
      this.messages.push(response);
      this.renderMessage(response);
    } catch (error) {
      loadingEl.remove();
      const errorMessage = {
        role: "model",
        content: `Error: ${error instanceof Error ? error.message : "Failed to get response"}`
      };
      this.messages.push(errorMessage);
      this.renderMessage(errorMessage);
    }
    this.isLoading = false;
    this.sendButton.disabled = false;
    this.sendButton.textContent = "\u27A4";
    this.scrollToBottom();
  }
  renderMessage(message) {
    const msgEl = this.messagesContainer.createDiv({
      cls: `gemini-chat-message gemini-chat-message-${message.role}`
    });
    const avatarEl = msgEl.createDiv({ cls: "gemini-chat-avatar" });
    avatarEl.textContent = message.role === "user" ? "\u{1F464}" : "\u{1F916}";
    const contentEl = msgEl.createDiv({ cls: "gemini-chat-content" });
    import_obsidian4.MarkdownRenderer.renderMarkdown(
      message.content,
      contentEl,
      "",
      this
    );
    this.processCitationLinks(contentEl);
    if (message.citations && message.citations.length > 0) {
      const citationsEl = msgEl.createDiv({ cls: "gemini-chat-citations" });
      citationsEl.createEl("div", { cls: "gemini-chat-citations-label", text: "\u{1F4CE} Sources:" });
      for (const citation of message.citations) {
        const citationCard = citationsEl.createDiv({ cls: "gemini-chat-citation-card" });
        const citationLink = citationCard.createEl("a", {
          cls: "gemini-chat-citation-link",
          text: `\u{1F4C4} ${citation.sourcePath}`
        });
        citationLink.addEventListener("click", (e) => {
          e.preventDefault();
          this.openNote(citation.sourcePath);
        });
      }
    }
    this.scrollToBottom();
  }
  processCitationLinks(container) {
    var _a;
    const walker = document.createTreeWalker(container, NodeFilter.SHOW_TEXT);
    const textNodes = [];
    while (walker.nextNode()) {
      textNodes.push(walker.currentNode);
    }
    for (const textNode of textNodes) {
      const text = textNode.textContent || "";
      const pattern = /\[Source:\s*([^\]]+)\]/g;
      let match;
      let lastIndex = 0;
      const fragments = [];
      while ((match = pattern.exec(text)) !== null) {
        if (match.index > lastIndex) {
          fragments.push(text.slice(lastIndex, match.index));
        }
        const sourcePath = match[1];
        const link = document.createElement("a");
        link.className = "gemini-chat-inline-citation";
        link.textContent = `\u{1F4C4} ${sourcePath}`;
        link.href = "#";
        link.addEventListener("click", (e) => {
          e.preventDefault();
          this.openNote(sourcePath);
        });
        fragments.push(link);
        lastIndex = match.index + match[0].length;
      }
      if (lastIndex < text.length) {
        fragments.push(text.slice(lastIndex));
      }
      if (fragments.length > 1) {
        const span = document.createElement("span");
        for (const fragment of fragments) {
          if (typeof fragment === "string") {
            span.appendChild(document.createTextNode(fragment));
          } else {
            span.appendChild(fragment);
          }
        }
        (_a = textNode.parentNode) == null ? void 0 : _a.replaceChild(span, textNode);
      }
    }
  }
  async openNote(path) {
    let cleanPath = path.trim();
    if (!cleanPath.endsWith(".md")) {
      cleanPath += ".md";
    }
    const file = this.app.vault.getAbstractFileByPath(cleanPath);
    if (file instanceof import_obsidian4.TFile) {
      await this.app.workspace.openLinkText(cleanPath, "", true);
    } else {
      const fileName = cleanPath.split("/").pop() || cleanPath;
      const files = this.app.vault.getMarkdownFiles();
      const matchingFile = files.find(
        (f) => f.name === fileName || f.path.endsWith(cleanPath)
      );
      if (matchingFile) {
        await this.app.workspace.openLinkText(matchingFile.path, "", true);
      } else {
        new import_obsidian4.Notice(`Note not found: ${path}`);
      }
    }
  }
  clearChat() {
    this.messages = [];
    this.messagesContainer.empty();
    this.plugin.geminiService.clearChatHistory();
    this.showWelcomeMessage();
  }
  scrollToBottom() {
    setTimeout(() => {
      this.messagesContainer.scrollTop = this.messagesContainer.scrollHeight;
    }, 50);
  }
};

// src/main.ts
var GeminiSyncPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    console.log("Loading Gemini Sync Plugin");
    await this.loadSettings();
    this.geminiService = new GeminiService(this);
    this.syncEngine = new SyncEngine(this, this.geminiService);
    this.registerView(
      CHAT_VIEW_TYPE,
      (leaf) => new ChatView(leaf, this)
    );
    this.addRibbonIcon("message-square", "Open Gemini Chat", () => {
      this.activateChatView();
    });
    this.addSettingTab(new GeminiSyncSettingTab(this.app, this));
    this.statusBarItem = this.addStatusBarItem();
    this.updateStatusBar("Ready");
    if (this.settings.apiKey) {
      this.registerFileEvents();
    }
    this.addCommand({
      id: "open-gemini-chat",
      name: "Open Gemini Chat",
      callback: () => {
        this.activateChatView();
      }
    });
    this.addCommand({
      id: "force-sync-all",
      name: "Force Sync All Files",
      callback: async () => {
        if (!this.settings.apiKey) {
          new import_obsidian5.Notice("Please configure your Gemini API key first");
          return;
        }
        await this.syncEngine.fullSync();
      }
    });
    if (this.settings.apiKey && this.settings.syncFolder) {
      setTimeout(() => {
        this.syncEngine.initialSync();
      }, 2e3);
    }
  }
  onunload() {
    console.log("Unloading Gemini Sync Plugin");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.updateChatViewSyncStatus();
  }
  // Update sync status in chat view if it's open
  updateChatViewSyncStatus() {
    const leaves = this.app.workspace.getLeavesOfType(CHAT_VIEW_TYPE);
    if (leaves.length > 0) {
      const chatView = leaves[0].view;
      if (chatView && typeof chatView.updateSyncStatus === "function") {
        chatView.updateSyncStatus();
      }
    }
  }
  registerFileEvents() {
    this.registerEvent(
      this.app.vault.on("create", async (file) => {
        if (file instanceof import_obsidian5.TFile && this.shouldSync(file)) {
          console.log("File created:", file.path);
          await this.syncEngine.handleFileCreate(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (file instanceof import_obsidian5.TFile && this.shouldSync(file)) {
          console.log("File modified:", file.path);
          await this.syncEngine.handleFileModify(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", async (file) => {
        if (file instanceof import_obsidian5.TFile && this.shouldSync(file)) {
          console.log("File deleted:", file.path);
          await this.syncEngine.handleFileDelete(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", async (file, oldPath) => {
        if (file instanceof import_obsidian5.TFile) {
          const wasInSyncFolder = this.isInSyncFolder(oldPath);
          const isInSyncFolder = this.shouldSync(file);
          if (wasInSyncFolder || isInSyncFolder) {
            console.log("File renamed:", oldPath, "->", file.path);
            await this.syncEngine.handleFileRename(file, oldPath);
          }
        }
      })
    );
  }
  shouldSync(file) {
    if (!this.settings.syncFolder)
      return false;
    if (file.extension !== "md")
      return false;
    return this.isInSyncFolder(file.path);
  }
  isInSyncFolder(path) {
    if (!this.settings.syncFolder)
      return false;
    return path.startsWith(this.settings.syncFolder);
  }
  updateStatusBar(status) {
    this.statusBarItem.setText(`Gemini: ${status}`);
  }
  async activateChatView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(CHAT_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: CHAT_VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
/*! Bundled license information:

@google/generative-ai/dist/index.mjs:
  (**
   * @license
   * Copyright 2024 Google LLC
   *
   * Licensed under the Apache License, Version 2.0 (the "License");
   * you may not use this file except in compliance with the License.
   * You may obtain a copy of the License at
   *
   *   http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing, software
   * distributed under the License is distributed on an "AS IS" BASIS,
   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   * See the License for the specific language governing permissions and
   * limitations under the License.
   *)

@google/generative-ai/dist/index.mjs:
  (**
   * @license
   * Copyright 2024 Google LLC
   *
   * Licensed under the Apache License, Version 2.0 (the "License");
   * you may not use this file except in compliance with the License.
   * You may obtain a copy of the License at
   *
   *   http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing, software
   * distributed under the License is distributed on an "AS IS" BASIS,
   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   * See the License for the specific language governing permissions and
   * limitations under the License.
   *)
*/
